name: webapps_assignment
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  google_fonts: ^4.0.3
  iconsax: ^0.0.8
  get: ^4.6.5



flutter:

  uses-material-design: true

